name = "cloudflare-spike-client"
pages_build_output_dir = "public"
compatibility_date = "2026-05-15"

[dev]
port = 8787
inspector_port = 9230

[vars]
VERSION = "dev"

[[kv_namespaces]]
binding = "KV"
id = "2853921ca3614f8ca884828117c81d40"
