name = "cloudflare-spike-workflows"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true
preview_urls = true

[dev]
port = 8795
inspector_port = 9238

[[workflows]]
name = "spike-workflow"
binding = "WORKFLOW"
class_name = "SpikeWorkflow"

[vars]
VERSION = "dev"

[[routes]]
pattern = "cloudflare-spike.iaingalloway.com/workflows*"
zone_name = "iaingalloway.com"
