name = "cloudflare-spike-cache"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true
preview_urls = true

[dev]
port = 8789
inspector_port = 9232

[vars]
VERSION = "dev"

[[routes]]
pattern = "cloudflare-spike.iaingalloway.com/cache*"
zone_name = "iaingalloway.com"
