name = "cloudflare-spike-do"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true
preview_urls = true

[dev]
port = 8791
inspector_port = 9234

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]

[vars]
VERSION = "dev"

[[routes]]
pattern = "cloudflare-spike.iaingalloway.com/do*"
zone_name = "iaingalloway.com"
