name = "cloudflare-spike"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true
preview_urls = true

[dev]
port = 8788
inspector_port = 9231

[vars]
VERSION = "dev"

[[routes]]
pattern = "cloudflare-spike.iaingalloway.com/worker*"
zone_name = "iaingalloway.com"
