name = "cloudflare-spike-d1"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true
preview_urls = true

[dev]
port = 8790
inspector_port = 9233

[[d1_databases]]
binding = "DB"
database_name = "spike-d1"
database_id = "a88fcdca-0b89-48b0-b67b-590fb3a28619"

[vars]
VERSION = "dev"

[[routes]]
pattern = "cloudflare-spike.iaingalloway.com/d1*"
zone_name = "iaingalloway.com"
